### ISSUE TITLE
Ignore install option

### ISSUE THREAD

**Issue by nonlux** [ericclemmons/npm-install-webpack-plugin#85]
Hi!
How can I say  to plugin  ignore  to install some package?

**Comment by ericclemmons** [comment]
Why ignore it?  Is it already installed somewhere?

**Comment by nonlux** [comment]
Yes. As  example:
  I use Happypack (https://github.com/amireh/happypack)
 My config example: https://github.com/nonlux/nlx-webpack-config/blob/master/basic.config.js

Your plugin try to load happypack-loader every time, but it in happypack package.

**Comment by ericclemmons** [comment]
Man, congrats on getting happypack to work!

If `node_modules/happypack-loader` exists, then #80 may fix this!

**Comment by nonlux** [comment]
Thx )
Happypack use own loader:
'happypack/loader'   => node_modules/happypack/loader.js
Not 'happypack-loader'.
Module happypack-loader is not exists (

But 'NpmInstallPlugin' want it.

**Comment by nonlux** [comment]
May be it plugin bug?
[This](https://github.com/nonlux/nlx-webpack-config/blob/master/basic.config.js#L102) not require happypack-loader package.

**Comment by leosuncin** [comment]
I have an issue with `react-hot-loader`, the plugin try to install a package named `babel-plugin-react-hot-loader/babel` and fail.
```bash
Installing babel-plugin-react-hot-loader/babel...
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/babel-plugin-react-hot-loader/babel.git
npm ERR!
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leosuncin/.npm/_logs/2018-01-23T18_15_28_007Z-debug.log
```

.babelrc
```json
{
  "presets": [
    [
      "env",
      {
        "debug": true,
        "modules": false,
        "useBuiltIns": true
      }
    ],
    "stage-0",
    "react"
  ],
  "plugins": ["transform-pipeline", "react-hot-loader/babel"]
}
```

<details>
<summary>debug.log</summary>
<pre>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'babel-plugin-react-hot-loader/babel',
1 verbose cli   '--save' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose npm-session c5c877999439b5f8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for github:babel-plugin-react-hot-loader/babel Error while executing:
7 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t ssh://git@github.com/babel-plugin-react-hot-loader/babel.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData ERROR: Repository not found.
7 silly fetchPackageMetaData fatal: Could not read from remote repository.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData Please make sure you have the correct access rights
7 silly fetchPackageMetaData and the repository exists.
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData exited with error code: 128
8 verbose stack Error: exited with error code: 128
8 verbose stack     at ChildProcess.onexit (/usr/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
8 verbose stack     at ChildProcess.emit (events.js:160:13)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
9 verbose cwd /home/leosuncin/Workspaces/github/wikipedia-react-webapp
10 verbose Linux 4.14.13-1-MANJARO
11 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "babel-plugin-react-hot-loader/babel" "--save"
12 verbose node v9.4.0
13 verbose npm  v5.6.0
14 error Error while executing:
14 error /usr/bin/git ls-remote -h -t ssh://git@github.com/babel-plugin-react-hot-loader/babel.git
14 error
14 error ERROR: Repository not found.
14 error fatal: Could not read from remote repository.
14 error
14 error Please make sure you have the correct access rights
14 error and the repository exists.
14 error
14 error exited with error code: 128
15 verbose exit [ 1, true ]
</pre>
</details>

> **Packages version**
> webpack v3.10.0
> npm-install-webpack-plugin v4.0.5
> react-hot-loader v4.0.0-beta.17
